#!/bin/sh

find /lib/modules/$(uname -r) -name v4l2-common.ko -exec /sbin/modprobe v4l2-common \;
find /lib/modules/$(uname -r) -name videobuf2-core.ko -exec /sbin/modprobe videobuf2-core \;
find /lib/modules/$(uname -r) -name videobuf2-common.ko -exec /sbin/modprobe videobuf2-common \;
find /lib/modules/$(uname -r) -name videobuf2-vmalloc.ko -exec /sbin/modprobe videobuf2-vmalloc \;
find /lib/modules/$(uname -r) -name videobuf2-v4l2.ko -exec /sbin/modprobe videobuf2-v4l2 \;
find /lib/modules/$(uname -r) -name snd.ko -exec /sbin/modprobe snd \;
find /lib/modules/$(uname -r) -name snd-pcm.ko -exec /sbin/modprobe snd-pcm \;
/sbin/rmmod ntv2video.ko && /sbin/insmod ntv2video.ko || /sbin/insmod ntv2video.ko

# find ntv2dev major number
major=`cat /proc/devices | awk "\\$2==\"ntv2dev\" {print \\$1}"`

# remove and insert nodes
rm -f /dev/ajantv2[0-3]
mknod /dev/ajantv20 c $major 0
mknod /dev/ajantv21 c $major 1
mknod /dev/ajantv22 c $major 2
mknod /dev/ajantv23 c $major 3

chmod 666 /dev/ajantv2[0-3]

rm -f /dev/oem2k[0-3]
mknod /dev/oem2k0 c $major 0
mknod /dev/oem2k1 c $major 1
mknod /dev/oem2k2 c $major 2
mknod /dev/oem2k3 c $major 3

chmod 666 /dev/oem2k[0-3]
